export const ActionTypes = {
  RETRIEVE_STATE_SUCCESS: "RETRIEVE_STATE_SUCCESS",
  CACHE_LINKED_FIELD_ELEMENT: "CACHE_LINKED_FIELD_ELEMENT",
  ADD_SNAPSHOT_SUCCESS: "ADD_SNAPSHOT_SUCCESS",
  ADD_SNAPSHOT: "ADD_SNAPSHOT",
};